name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["20.x", "22.x", "24.x"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (v${{ matrix.node }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Lint Check
        run: bun run lint

      - name: Type Check
        run: bun run check

      - name: Build Check
        run: bun run build

      - name: Test
        run: bun test
